# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
from pathlib import Path
import PyQt5
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QMessageBox

output_path = None
ui_file = None


class Ui_window(QtWidgets.QWidget):
    def setupUi(self, window):
        window.setObjectName("window")
        window.resize(421, 268)
        self.win = window

        self.centralwidget = QtWidgets.QWidget(window)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 20, 141, 71))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.ui_file)

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(240, 20, 141, 71))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.output_path)

        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(190, 100, 113, 21))
        self.lineEdit.setObjectName("lineEdit")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 100, 131, 21))

        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)

        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")

        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(120, 140, 181, 71))
        self.pushButton_3.clicked.connect(self.convert)

        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)

        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")


        window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 421, 21))
        self.menubar.setObjectName("menubar")
        window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(window)
        self.statusbar.setObjectName("statusbar")
        window.setStatusBar(self.statusbar)

        self.retranslateUi(window)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "UI to PY convertor"))
        self.pushButton.setText(_translate("window", "Select UI File"))
        self.pushButton_2.setText(_translate("window", "Select Output Folder"))
        self.label.setText(_translate("window", "Python file name:"))
        self.pushButton_3.setText(_translate("window", "CONVERT"))

    def output_path(self):
        global output_path
        output_path = QtWidgets.QFileDialog.getExistingDirectory(
            caption='Select Output Folder'
        )


    def ui_file(self):
        global ui_file

        file_filter = 'UI File (*.ui);;'

        ui_file = QtWidgets.QFileDialog.getOpenFileName(
            parent=self,
            caption='Select a UI File',
            directory=os.getcwd(),
            filter=file_filter
        )




    def convert(self):
        global ui_file
        global output_path

        try:
            if ui_file == None:
                QMessageBox.critical(self, "Error!", "You need to choose a UI file first!")
            else:
                ui_file = ui_file[0]
            if output_path == None:
                output_path = Path(ui_file).parent.absolute()
            print(f'Output path: {output_path}  ||  UI_File: {ui_file}')
            file_name = self.lineEdit.text()
            if file_name == '':
                file_name = os.path.basename(ui_file)
                file_name = file_name.split('.')[0]

            os.popen(f"python -m PyQt5.uic.pyuic -x {ui_file} -o {os.path.join(output_path, file_name) + '.py'}")
            QMessageBox.information(self, "Success!",
                                    f"We successfully converted your .ui file to a .py file! its located in {output_path}")
        except:
            print('No UI file chosen!')



import sys
app = QtWidgets.QApplication(sys.argv)
window = QtWidgets.QMainWindow()
ui = Ui_window()
ui.setupUi(window)
window.show()
sys.exit(app.exec_())
